stages:
  preprocess:
    cmd: python3 src/preprocess.py 
    deps:
      - src/preprocess.py
      - data/
    params:
      - preprocess.input
      - preprocess.output
    outs:
      - feature/preprocess
  
  split:
    cmd: python3 src/split.py
    deps:
      - src/split.py
      - feature/preprocess
    params:
      - split.n_splits
      - split.csv_path
      - split.train_path
      - split.test_path
    outs:
      - split/train
      - split/test
    
  train:
    cmd: python3 src/trainning.py
    deps:
      - src/trainning.py
      - split/train
    params:
      - train.cv
      - train.model_path
      - train.train_csv
      - train.n_estimators
      - train.criterion
      - train.max_depth
      - train.min_samples_split
      - train.min_samples_leaf
      - train.bootstrap
      - train.random_state
    outs:
      - model/
  
  eval:
    cmd: python3 src/eval.py
    deps:
      - src/eval.py
      - split/test/eval.csv
      - model/model.pkl
    params:
      - eval.model_path
      - eval.eval_csv
      - eval.score
    outs:
      - metrics/