stages:
  preprocess:
    cmd: python3 src/preprocess.py 
    deps:
      - src/preprocess.py
      - data/
    params:
      - preprocess.input
      - preprocess.output
    outs:
      - feature/preprocess