preprocess:
  input: data/train.csv
  output: feature/preprocess

split:
  n_splits: 5
  csv_path: feature/preprocess/preprocessed.csv
  train_path: split/train
  test_path: split/test

train:
  cv: 5
  model_path: model
  train_csv: split/train/train_split.csv
  num_boost_round: 100
  max_depth: 4
  learning_rate: 0.05
  objective: 'binary:logistic'
  verbosity: 0
  eval_metric: 'auc'
  early_stopping_rounds: 150

eval:
  model_path: "model/model.pkl"
  eval_csv: "split/test/eval.csv"
  score: "metrics/"