name: Stroke Predictions
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-tools@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_AUTH }}
        run: |
          dvc pull
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro
          dvc push
          
          echo "## Model metrics" > report.md
          dvc metrics diff --show-md >> report.md
          echo >> report.md

          
          cml comment create report.md